site_name: DigitalSaucepan
copyright: Copyright &copy; 2017 DigitalSaucepan

theme: 'material'
extra:
  palette:
    primary: 'deep orange'
    accent: 'deep orange'

pages:
  - Introduction: 'index.md'
  - DigiWeight: 'digiweight.md'
  - DigiBP: 'digibp.md'

markdown_extensions:
  - admonition
